import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import About from '@/components/About'
import Skills from '@/components/Skills'
import Projects from '@/components/Projects'
import Contact from '@/components/Contact'
import Main from '@/components/Main'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

  
      <section >
        <Main></Main>
      </section>
    <section >
    <About></About>
    </section>
      <section>
      <Skills></Skills>
      </section>
   <section>
   <Projects></Projects>
   </section>
   <section >
   <Contact></Contact>
   </section>
    </>
  )
}
